### ISSUE TITLE
[MELHORIA] Autenticação do projeto.

### ISSUE THREAD

**Issue by lucaslmmanoel** [lucaslmmanoel/project_controller#3]
- [x] Implementar autenticação do projeto.

php artisan make:auth

**Comment by dougs007** [comment]
Foi implementado porém não será criado o construtor nas model's por enquanto, vamos criar o sistema e deixar livre para ser feito o desenvolvimento sem problems.

**Comment by dougs007** [comment]
Branch: feature-backend
