### ISSUE TITLE
[MELHORIA] Tela de administração de Tipos de projetos.

### ISSUE THREAD

**Issue by dougs007** [lucaslmmanoel/project_controller#5]
- [x] Criar crud com exclusão lógica de tipos de projeto.

obs: A exclusão lógica será um update na tabela desativando o status do tipo de projeto.

Um tipo de projeto seria -> Software, Inclusão Digital e etc ...

**Comment by dougs007** [comment]
Demanda atendida!

**Comment by lucaslmmanoel** [comment]
eu irei melhorar o layout e pode fechar essa isssue beleza?

**Comment by lucaslmmanoel** [comment]
Acho que temos que criar uma função de ativar o projeto né?
